# USED PIN
## Switches
set_property PACKAGE_PIN V17 [get_ports {in_number[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[0]}]
set_property PACKAGE_PIN V16 [get_ports {in_number[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[1]}]
set_property PACKAGE_PIN W16 [get_ports {in_number[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[2]}]
set_property PACKAGE_PIN W17 [get_ports {in_number[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[3]}]
set_property PACKAGE_PIN W15 [get_ports {in_number[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[4]}]
set_property PACKAGE_PIN V15 [get_ports {in_number[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[5]}]
set_property PACKAGE_PIN W14 [get_ports {in_number[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[6]}]
set_property PACKAGE_PIN W13 [get_ports {in_number[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[7]}]
set_property PACKAGE_PIN V2 [get_ports {in_number[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[8]}]
set_property PACKAGE_PIN T3 [get_ports {in_number[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {in_number[9]}]
#LEDS
set_property PACKAGE_PIN U16 [get_ports {out_bcd[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_bcd[0]}]
set_property PACKAGE_PIN E19 [get_ports {out_bcd[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_bcd[1]}]
set_property PACKAGE_PIN U19 [get_ports {out_bcd[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_bcd[2]}]
set_property PACKAGE_PIN V19 [get_ports {out_bcd[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_bcd[3]}]
